### PR TITLE
Non-working HTTP basic authentication was fixed

### PR DESCRIPTION
**Pull request by artiomn**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	Basic auth didn't work, because script was trying to decipher base64-encoded login/password.
        Fixed.

### CODE REVIEW

**Comment by artiomn** [comment]
Is there anyone alive?

**Comment by tobbenb** [comment]
Isn't this something you should PR to the author of the script?

**Comment by aptalca** [comment]
@artiomn can you describe what issue this is attempting to fix? I don't understand what ldap auth has anything to do with http auth. You should be using one or the other, not both.

Aslo as @tobbenb said, we're not the devs of the daemon running here, we just packaged it along with the frontend in a docker image.

**Comment by artiomn** [comment]
@tobbenb, @aptalca, yes I know, of course.
But I use this "reference implementation" with your container and I thought, that Linuxserver command fixed it, because I have read following comments inside the script:

> # Copyright (C) 2018 LinuxServer.io

@aptalca, this script will set the cookie for the service when authenticated.
And the script has a couple of credentials reading mechanisms: an HTML page with a form and an “HTTP Basic Auth”.
When I use HTTP Basic Auth, the script does not work, because the browser sends the credentials as a string encoded in base64, but the script assumes that the credentials are encrypted using a fixed key (as in the HTML page version).

**Comment by aptalca** [comment]
Ah, now I get it.

Honestly, this implementation was done completely with the form/cookie in mind. I did not even consider the non-cookie option.

Yes, you are correct that the fernet method breaks the http auth method for the daemon. I'll do some testing.

Thanks

**Comment by artiomn** [comment]
> Honestly, this implementation was done completely with the form/cookie in mind.

Wait, both variants use cookie. Yes, variant with form is more convenient, but it doesn't work for me (I'll try to make it work in the near future, but now I use HTTP basic auth + TLS).

> I did not even consider the non-cookie option.

The developers of this code implemented this variant.

> Yes, you are correct that the fernet method (the only change we made to the daemon) breaks the http auth method for the daemon. I'll do some testing.

Ok, thanks.

**Comment by aptalca** [comment]
The login form that is on the original project's repo saves the username and password in a cookie, base64 encoded, which is really insecure (they also admit it at the bottom of their readme). We created this project to encode that with fernet instead, which is a lot more secure. A randomized fernet key is created on container creation and the same key is used by the form to encode and the daemon to decode.

I'm investigating the http auth option to see what is saved where

**Comment by artiomn** [comment]
> The login form that is on the original project's repo saves the username and password in a cookie, base64 encoded, which is really insecure (they also admit it at the bottom of their readme).

Yes, if you use HTTP, but not with HTTPS.

Thanks.

**Pull request merged**
